meta-dataset:
  load_only_dataset_descriptors: true
  model_args_first: true
  root: /home/evilknivl/projects/edit-qt-mds/mtlbm-metadataset
  standardize_num_args: true
  version: mini

search_space:
  path: None
  config: None

surrogate_config:
  cost_aware: true
  cost_predictor:
    encoder_dim_ranges:
      - 24
      - 69
    encoder_num_layers: 2
    hidden_dim: 128
    in_curves_dim: 1
    in_metafeatures_dim: 4
    out_curves_dim: 128
    out_metafeatures_dim: 16
    output_dim: 1
  feature_extractor:
    encoder_dim_ranges:
      - 24
      - 69
    encoder_num_layers: 2
    hidden_dim: 128
    in_curves_dim: 1
    in_metafeatures_dim: 4
    out_curves_dim: 128
    out_metafeatures_dim: 16
    output_dim: 128
  include_metafeatures: true
  lr: 0.001
