metaset:
  load_only_dataset_descriptors: true
  model_args_first: true
  root: /home/evilknivl/projects/edit-qt-mds/mtlbm-metadataset
  standardize_num_hps: true
  version: mini

configuration-manager:
  path: "*mtlbm*"
  configspace: null

optimizer:
  surrogate:
    cost_aware: true
    cost_predictor:
      in_features: null
      hidden_features: 32
      in_curve_dim: 1
      out_curve_dim: 16
      in_meta_features: 4
      out_meta_features: 16
      out_features: 32
      enc_num_layers: 0
    feature_extractor:
      hidden_features: 32
      in_features: null
      in_curve_dim: 1
      out_curve_dim: 16
      in_meta_features: 4
      out_meta_features: 16
      out_features: 32
      enc_num_layers: 2
      enc_slice_ranges:
        - 24

    meta-train: false
    meta-train-config:
      batch_size: 128
      lr: 0.0001
      patience: 10
      train_iter: 1000
      val_iter: 50
      val_freq: 20
      weight_decay: 0.0
      use_scheduler: true
  
    lr: 0.0001
    
  num_configs: 100


  load_from_pretrained: true
  pretrained_path: "/home/evilknivl/projects/quicktunetool/scripts/.cache/meta/model.pt"
  meta_train: true

experiment:
  dataset: imagenetest
  train-split: train
  val-split: val
  num_classes: 10
  data_path: "/home/evilknivl/projects/datasets/imagenettest"
  metafeatures: null
  output_dir: experiment
  budget: 50