metaset:
  load_only_dataset_descriptors: true
  model_args_first: true
  root: "*mtlbm*"
  standardize_num_hps: true
  version: micro

configuration-manager:
  path: "*mtlbm*"

optimizer:
  surrogate:
    cost_predictor:
      in_features: 71
    feature_extractor:
      in_features: 71
      enc_num_layers: 2
      enc_slice_ranges:
        - 24
    lr: 0.001
  num_configs: 100
  load_from_pretrained: true
  pretrained_path: "*mtlbm*"
